version: '3'
services:
  shopix-store-db:
    image: mysql
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: madara
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: auctionWave
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "shopix-store-vol:/var/lib/mysql"
networks:
  shopix-store-net:
volumes:
  shopix-store-vol:
