version: '3.8'

services:
  database:
    image: postgres:14
    container_name: hibernate-demo-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - hibernate-demo-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  hibernate-demo-network:
    driver: bridge

volumes:
  postgres_data: